In [1]:
%run 00_functions.ipynb

c:\Users\nyy32\OneDrive\Documents\UM_Master of Artifcial Inteligence\Thesis\Github\Cryptocurrency Forecasting\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Load the collected Bitcoin news dataset
news_path = Path("../data/news/raw/bitcoin_news_72h.csv")
news_df = pd.read_csv(news_path)

print("========== Dataset Overview ==========")
print("File:", news_path.resolve())
print("Total articles:", len(news_df))
print("Columns:", news_df.columns.tolist())

print("\n========== First 5 Articles ==========")
display(news_df.head())

========== Dataset Overview ==========
File: C:\Users\nyy32\OneDrive\Documents\UM_Master of Artifcial Inteligence\Thesis\Github\Cryptocurrency Forecasting\data\news\raw\bitcoin_news_72h.csv
Total articles: 129
Columns: ['title', 'source', 'published_at_utc', 'link', 'summary', 'content', 'content_status']

========== First 5 Articles ==========

,title,source,published_at_utc,link,summary,content,content_status
0,Bitcoin ETFs lose $679 million over the week,Yahoo Finance Video,2026-10-12T17:00:00+00:00,https://finance.yahoo.com/video/bitcoin-etfs-l...,Scott Melker discusses how bitcoin ETFs lost $...,Scott Melker discusses how bitcoin ETFs lost $...,summary_and_content
1,The Whale Behind $29.75 Million in Wins Just W...,BeInCrypto,2026-10-13T07:51:27+00:00,https://finance.yahoo.com/markets/crypto/artic...,A Hyperliquid whale with $29.75 million in pro...,Leveraged bulls lost $688.56 million to liquid...,summary_and_content
2,"Cleveland Fed President Wants Small, Quick Rat...",BeInCrypto,2026-10-13T06:21:09+00:00,https://finance.yahoo.com/markets/crypto/artic...,Fed’s Hammack backs restrictive policy as Dece...,Cleveland Fed President Beth Hammack said that...,summary_and_content
3,Bulls Absorb 89% of $774 Million Crypto Liquid...,BeInCrypto,2026-10-13T01:59:15+00:00,https://finance.yahoo.com/markets/crypto/artic...,"Crypto liquidations hit $774 million, with lon...",Leveraged bulls took the brunt of a $774.14 mi...,summary_and_content
4,When Will Bitcoin Price Reclaim Its All-Time H...,BeInCrypto,2026-10-12T23:13:49+00:00,https://finance.yahoo.com/markets/crypto/artic...,Cycle data shows how fast Bitcoin could reclai...,Bitcoin price currently trades 35% below its r...,summary_and_content

In [3]:
# Check for duplicate records and missing values

print("========== 1. Duplicate Check ==========")
print("Duplicate links:", news_df["link"].duplicated().sum())
print("Duplicate titles:", news_df["title"].duplicated().sum())

print("\n========== 2. Missing Values ==========")
print(news_df[
    ["title", "source", "published_at_utc",
     "link", "summary", "content", "content_status"]
].isna().sum())

print("\n========== 3. Empty Text Check ==========")
print("Empty titles:",
      news_df["title"].fillna("").str.strip().eq("").sum())
print("Empty links:",
      news_df["link"].fillna("").str.strip().eq("").sum())
print("Empty content:",
      news_df["content"].fillna("").str.strip().eq("").sum())

print("\n========== 4. Content Status ==========")
print(news_df["content_status"].value_counts(dropna=False))

print("\n========== 5. Content Length ==========")
content_length = news_df["content"].fillna("").str.len()
print("Minimum content length:", content_length.min())
print("Content under 500 characters:", (content_length < 500).sum())

print("\n========== 6. Summary Check ==========")
summary = news_df["summary"].fillna("").str.strip()
content = news_df["content"].fillna("").str.strip()

print("Summary is None/empty:", summary.eq("").sum())
print("Summary identical to content:", (summary == content).sum())

========== 1. Duplicate Check ==========
Duplicate links: 0
Duplicate titles: 0

========== 2. Missing Values ==========
title               0
source              0
published_at_utc    0
link                0
summary             8
content             0
content_status      0
dtype: int64

========== 3. Empty Text Check ==========
Empty titles: 0
Empty links: 0
Empty content: 0

========== 4. Content Status ==========
content_status
summary_and_content    121
content_only             8
Name: count, dtype: int64

========== 5. Content Length ==========
Minimum content length: 100
Content under 500 characters: 8

========== 6. Summary Check ==========
Summary is None/empty: 8
Summary identical to content: 0

In [4]:
# Check publication timestamps against the latest 72-hour window

from datetime import datetime, timezone

check_time = datetime.now(timezone.utc)
cutoff_time = pd.Timestamp(check_time) - pd.Timedelta(hours=72)

news_df["published_at_utc"] = pd.to_datetime(
    news_df["published_at_utc"],
    utc=True,
    errors="coerce"
)

invalid_timestamps = news_df["published_at_utc"].isna()

outside_window = (
    (news_df["published_at_utc"] < cutoff_time) |
    (news_df["published_at_utc"] > pd.Timestamp(check_time))
) & ~invalid_timestamps

print("========== Publication Time Check ==========")
print("Check time (UTC):", check_time.isoformat())
print("72-hour cutoff (UTC):", cutoff_time.isoformat())
print("Invalid timestamps:", invalid_timestamps.sum())
print("Articles outside 72-hour window:", outside_window.sum())

valid_times = news_df.loc[
    ~invalid_timestamps, "published_at_utc"
]

if not valid_times.empty:
    print("Newest article (UTC):", valid_times.max())
    print("Oldest article (UTC):", valid_times.min())

if outside_window.any():
    print("\nArticles outside the 72-hour window:")
    display(
        news_df.loc[
            outside_window,
            ["title", "published_at_utc", "link"]
        ]
    )

# Filter articles within the latest 72 hours
recent_news_df = news_df.loc[
    news_df["published_at_utc"].between(
        cutoff_time,
        pd.Timestamp(check_time),
        inclusive="both"
    )
].copy()

print("Articles within the latest 72 hours:", len(recent_news_df))

========== Publication Time Check ==========
Check time (UTC): 2026-10-13T08:13:41.235360+00:00
72-hour cutoff (UTC): 2026-10-10T08:13:41.235360+00:00
Invalid timestamps: 0
Articles outside 72-hour window: 0
Newest article (UTC): 2026-10-13 07:51:27+00:00
Oldest article (UTC): 2026-10-10 09:48:00+00:00
Articles within the latest 72 hours: 129

In [5]:
# Identify articles that may be unrelated to Bitcoin or cryptocurrency

import re

crypto_keywords = [
    "bitcoin", "btc", "cryptocurrency", "crypto",
    "blockchain", "digital asset", "digital assets",
    "bitcoin etf", "crypto etf"
]

def check_crypto_relevance(row):
    text = f"{row['title']} {row['summary']} {row['content']}"
    text = text.lower()
    return any(
        re.search(r"\b" + re.escape(keyword) + r"\b", text)
        for keyword in crypto_keywords
    )

news_df["keyword_relevant"] = news_df.apply(
    check_crypto_relevance, axis=1
)

potentially_irrelevant = news_df[
    ~news_df["keyword_relevant"]
]

print("Total articles:", len(news_df))
print("Potentially relevant:", news_df["keyword_relevant"].sum())
print("Potentially irrelevant:", len(potentially_irrelevant))

display(
    potentially_irrelevant[
        ["title", "source", "summary"]
    ]
)

Total articles: 129
Potentially relevant: 124
Potentially irrelevant: 5

,title,source,summary
8,Sector Update: Financial Stocks Advance Late A...,MT Newswires,NaN
12,IREN Reportedly Joins Anthropic's Cloud Provid...,Investor's Business Daily,NaN
17,Sector Update: Financial Stocks Rise Monday Af...,MT Newswires,NaN
19,Anthropic Deal Report Gives IREN Stock Early B...,Barrons.com,NaN
39,"Exchange-Traded Funds Lower, Equity Futures Mi...",MT Newswires,NaN

In [6]:
# Inspect potentially irrelevant articles before making any decisions

review_columns = ["title", "source", "link", "content"]

for index, row in potentially_irrelevant.iterrows():
    print("\n" + "=" * 100)
    print(f"Index: {index}")
    print(f"Title: {row['title']}")
    print(f"Source: {row['source']}")
    print(f"Link: {row['link']}")
    print(f"Content length: {len(str(row['content']))}")
    print("\nFull content:")
    print(row["content"])

====================================================================================================
Index: 8
Title: Sector Update: Financial Stocks Advance Late Afternoon
Source: MT Newswires
Link: https://finance.yahoo.com/markets/stocks/articles/sector-financial-stocks-advance-afternoon-200011423.html
Content length: 100

Full content:
Financial stocks rose in late Monday afternoon trading, with the NYSE Financial Index adding 0.5% an

====================================================================================================
Index: 12
Title: IREN Reportedly Joins Anthropic's Cloud Providers; Shares Jump
Source: Investor's Business Daily
Link: https://finance.yahoo.com/m/04ab5ce8-c2c2-3b1c-952c-5ea1b7a9d653/iren-reportedly-joins.html
Content length: 123

Full content:
Anthropic reportedly signed a cloud services deal with IREN as it accelerates its data center buildouts. IREN stock surges.

====================================================================================================
Index: 17
Title: Sector Update: Financial Stocks Rise Monday Afternoon
Source: MT Newswires
Link: https://finance.yahoo.com/markets/stocks/articles/sector-financial-stocks-rise-monday-175415678.html
Content length: 100

Full content:
Financial stocks rose in Monday afternoon trading with the NYSE Financial Index and the State Street

====================================================================================================
Index: 19
Title: Anthropic Deal Report Gives IREN Stock Early Boost Before Gains Fade
Source: Barrons.com
Link: https://finance.yahoo.com/m/1a6521f3-c066-33d2-ab8c-c609e2bd6c19/anthropic-deal-report-gives.html
Content length: 142

Full content:
Anthropic may well be the unnamed frontier AI lab that IREN said it had signed a cloud contract with when it reported fourth-quarter earnings.

====================================================================================================
Index: 39
Title: Exchange-Traded Funds Lower, Equity Futures Mixed Pre-Bell Monday as Investors Weigh Oil, Earnings
Source: MT Newswires
Link: https://finance.yahoo.com/markets/stocks/articles/exchange-traded-funds-lower-equity-130027583.html
Content length: 100

Full content:
The broad market exchange-traded fund SPDR S&P 500 ETF Trust (SPY) was up 0.03%, and the actively tr

In [7]:
# Keyword-based filtering after the 72-hour date filter
crypto_keywords = [
    "bitcoin",
    "btc",
    "cryptocurrency",
    "cryptocurrencies",
    "crypto",
    "blockchain",
    "digital asset",
    "digital assets"
]

def is_crypto_related(row):
    fields = [
        row.get("title", ""),
        row.get("summary", ""),
        row.get("content", "")
    ]

    text = " ".join(
        "" if pd.isna(value) else str(value)
        for value in fields
    ).lower()

    return any(
        re.search(
            r"\b" + re.escape(keyword) + r"\b",
            text
        )
        for keyword in crypto_keywords
    )


# Keep the original datasets unchanged
keyword_mask = recent_news_df.apply(
    is_crypto_related, axis=1
)

keyword_filtered_df = recent_news_df.loc[
    keyword_mask
].copy()

excluded_news_df = recent_news_df.loc[
    ~keyword_mask
].copy()

print("========== Keyword Filtering Summary ==========")
print("Articles after date filtering:", len(recent_news_df))
print("Keyword-relevant articles:", len(keyword_filtered_df))
print("Articles excluded by keyword filter:", len(excluded_news_df))

print("\n========== Excluded Articles ==========")
display(
    excluded_news_df[
        ["title", "source", "published_at_utc"]
    ]
)

========== Keyword Filtering Summary ==========
Articles after date filtering: 129
Keyword-relevant articles: 124
Articles excluded by keyword filter: 5

========== Excluded Articles ==========

,title,source,published_at_utc
8,Sector Update: Financial Stocks Advance Late A...,MT Newswires,2026-10-12 20:00:11+00:00
12,IREN Reportedly Joins Anthropic's Cloud Provid...,Investor's Business Daily,2026-10-12 20:22:57+00:00
17,Sector Update: Financial Stocks Rise Monday Af...,MT Newswires,2026-10-12 17:54:15+00:00
19,Anthropic Deal Report Gives IREN Stock Early B...,Barrons.com,2026-10-12 18:58:00+00:00
39,"Exchange-Traded Funds Lower, Equity Futures Mi...",MT Newswires,2026-10-12 13:00:27+00:00

In [8]:
print("Date-filtered articles:", len(recent_news_df))
print("Keyword-filtered articles:", len(keyword_filtered_df))
print("Excluded articles:", len(excluded_news_df))

print("\nRetained article sample:")
display(
    keyword_filtered_df[
        ["title", "source", "published_at_utc"]
    ].head(5)
)

Date-filtered articles: 129
Keyword-filtered articles: 124
Excluded articles: 5

Retained article sample:

,title,source,published_at_utc
0,Bitcoin ETFs lose $679 million over the week,Yahoo Finance Video,2026-10-12 17:00:00+00:00
1,The Whale Behind $29.75 Million in Wins Just W...,BeInCrypto,2026-10-13 07:51:27+00:00
2,"Cleveland Fed President Wants Small, Quick Rat...",BeInCrypto,2026-10-13 06:21:09+00:00
3,Bulls Absorb 89% of $774 Million Crypto Liquid...,BeInCrypto,2026-10-13 01:59:15+00:00
4,When Will Bitcoin Price Reclaim Its All-Time H...,BeInCrypto,2026-10-12 23:13:49+00:00

## SBERT

In [9]:
# Load the SBERT model
sbert_model = SentenceTransformer("all-MiniLM-L6-v2")

print("SBERT model loaded successfully.")
print("Embedding dimension:", sbert_model.get_sentence_embedding_dimension())

INFO: No device provided, using cpu
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/modules.json?%2Fsentence-transformers%2Fall-MiniLM-L6-v2%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config_sentence_transformers.json?%2Fsentence-transformers%2Fall-MiniLM-L6-v2%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22fd1b291129c607e5d49799f87cb219b27f98acdf%22 "HTTP/1.1 200 OK"
INFO: Loading SentenceTransformer model from sentence-transformers/all-MiniLM-L6-v2.
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/config_sentence_transformers.json?%2Fsentence-transformers%2Fall-MiniLM-L6-v2%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22fd1b291129c607e5d49799f87cb219b27f98acdf%22 "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING: Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/README.md?%2Fsentence-transformers%2Fall-MiniLM-L6-v2%2Fresolve%2Fmain%2FREADME.md=&etag=%2244af2e3b0fa3a0b6239e48422972bf755f28fde0%22 "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/modules.json?%2Fsentence-transformers%2Fall-MiniLM-L6-v2%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/sentence_bert_config.json?%2Fsentence-transformers%2Fall-MiniLM-L6-v2%2Fresolve%2Fmain%2Fsentence_bert_config.json=&etag=%2259d594003bf59880a884c574bf88ef7555bb0202%22 "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
INFO: HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2 "HTTP/1.1 200 OK"
INFO: HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2 "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5424.71it/s]
INFO: HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2 "HTTP/1.1 200 OK"
INFO: HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
INFO: HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
INFO: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-MiniLM-L6-v2/1110a243fdf4706b3f48f1d95db1a4f5529b4d41/1_Pooling%2Fconfig.json?%2Fsentence-transformers%2Fall-MiniLM-L6-v2%2Fresolve%2Fmain%2F1_Pooling%2Fconfig.json=&etag=%22d1514c3162bbe87b343f565fadc62e6c06f04f03%22 "HTTP/1.1 200 OK"
INFO: HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/2_Normalize/config.json "HTTP/1.1 404 Not Found"
INFO: HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L6-v2 "HTTP/1.1 200 OK"

SBERT model loaded successfully.
Embedding dimension: 384

C:\Users\nyy32\AppData\Local\Temp\ipykernel_34420\4262035451.py:5: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("Embedding dimension:", sbert_model.get_sentence_embedding_dimension())

In [10]:
# Define a neutral forecasting query
forecasting_query = """
Retrieve recent financial news relevant to Bitcoin (BTC) price forecasting,
including Bitcoin price movements, ETF flows, cryptocurrency market developments,
investor sentiment, regulatory developments, institutional adoption, and
macroeconomic events that may influence Bitcoin prices.
"""

# Prepare news text for SBERT
def build_article_text(row):
    text_parts = []

    for column in ["title", "summary", "content"]:
        value = row.get(column)

        if pd.notna(value) and str(value).strip():
            text_parts.append(
                f"{column.capitalize()}: {str(value).strip()}"
            )

    return "\n".join(text_parts)


news_texts = [
    build_article_text(row)
    for _, row in keyword_filtered_df.iterrows()
]

print("========== Query and Text Preparation ==========")
print("Forecasting query prepared:", bool(forecasting_query.strip()))
print("Candidate articles:", len(news_texts))
print("Empty article texts:", sum(not text.strip() for text in news_texts))

print("\n========== Forecasting Query ==========")
print(forecasting_query.strip())

print("\n========== First Article Text Preview ==========")
print(news_texts[0][:600] if news_texts else "No articles available.")

========== Query and Text Preparation ==========
Forecasting query prepared: True
Candidate articles: 124
Empty article texts: 0

========== Forecasting Query ==========
Retrieve recent financial news relevant to Bitcoin (BTC) price forecasting,
including Bitcoin price movements, ETF flows, cryptocurrency market developments,
investor sentiment, regulatory developments, institutional adoption, and
macroeconomic events that may influence Bitcoin prices.

========== First Article Text Preview ==========
Title: Bitcoin ETFs lose $679 million over the week
Summary: Scott Melker discusses how bitcoin ETFs lost $679 million over the past week, reversing the course of massive inflows.

"The Daily Wolf with Scott Melker" airs every day at 12:00 p.m. Tune in for your daily dose of all things crypto.

Make sure to also check out Yahoo Finance's new crypto hub to find the latest crypto-related news.
Content: Scott Melker discusses how bitcoin ETFs lost $679 million over the past week, reversing the course of massive inflows.

" The Daily Wolf with Scott Melker " airs every day at 12:00 p.m. Tune in fo

In [11]:
# 1. Encode the forecasting query
query_embedding = sbert_model.encode(
    forecasting_query,
    convert_to_tensor=True,
    show_progress_bar=False
)

# 2. Encode all candidate news articles
news_embeddings = sbert_model.encode(
    news_texts,
    convert_to_tensor=True,
    show_progress_bar=True
)

# 3. Calculate cosine similarity
similarity_scores = util.cos_sim(
    query_embedding,
    news_embeddings
).cpu().numpy().flatten()

# 4. Create a separate results DataFrame
semantic_results_df = keyword_filtered_df.copy()

semantic_results_df["similarity_score"] = similarity_scores

# 5. Rank articles by semantic similarity
semantic_results_df = (
    semantic_results_df
    .sort_values(
        by="similarity_score",
        ascending=False
    )
    .reset_index(drop=True)
)

semantic_results_df["similarity_rank"] = (
    range(1, len(semantic_results_df) + 1)
)

# 6. Display the retrieval summary
print("========== SBERT Retrieval Summary ==========")
print("Candidate articles:", len(news_texts))
print("Query embedding dimension:", query_embedding.shape[-1])
print("News embeddings shape:", tuple(news_embeddings.shape))
print("Similarity scores calculated:", len(similarity_scores))

print("\n========== Top 10 Retrieved Articles ==========")

display(
    semantic_results_df[
        [
            "similarity_rank",
            "title",
            "source",
            "published_at_utc",
            "similarity_score"
        ]
    ].head(10)
)

Batches: 100%|██████████| 4/4 [00:02<00:00,  1.69it/s]

========== SBERT Retrieval Summary ==========
Candidate articles: 124
Query embedding dimension: 384
News embeddings shape: (124, 384)
Similarity scores calculated: 124

========== Top 10 Retrieved Articles ==========

,similarity_rank,title,source,published_at_utc,similarity_score
0,1,Bitcoin Could Be Entering a New Bull Market De...,BeInCrypto,2026-10-11 19:22:47+00:00,0.626807
1,2,"Bitcoin and ethereum prices today, Monday, Oct...",Yahoo Personal Finance,2026-10-12 11:40:18+00:00,0.626133
2,3,Bitcoin slips to $82.6k as rise in oil prices ...,Investing.com,2026-10-12 07:08:56+00:00,0.605762
3,4,Bitcoin Ranges Near $83K as Traders Look to US...,decrypt,2026-10-12 11:41:50+00:00,0.584239
4,5,Bitcoin Tests Average Buyer’s Break-Even As ET...,Stocktwits,2026-10-10 17:34:25+00:00,0.576363
5,6,"Why Bitcoin Can Fall Before a Fed Rate Hike, T...",MoneyLion,2026-10-12 17:00:27+00:00,0.565969
6,7,"Bitcoin struggles above $83,000 a year after $...",Investing.com,2026-10-11 05:54:26+00:00,0.559304
7,8,"Crypto’s Crowded Longs Face a CPI Test, and a ...",CCN,2026-10-12 12:04:17+00:00,0.552340
8,9,Bitcoin Price Prediction: Golden Cross Signals...,FX Empire,2026-10-12 11:13:39+00:00,0.551598
9,10,AI Price Prediction: Insights from Grok on Bit...,24/7 Wall St.,2026-10-11 12:12:14+00:00,0.544206

In [12]:
# Select the top 10 retrieved news articles

TOP_K = 10

retrieved_news_df = semantic_results_df.head(TOP_K).copy()

print("Retrieved news prepared successfully.")
print("Selected articles:", len(retrieved_news_df))
print(
    "Similarity score range:",
    round(retrieved_news_df["similarity_score"].min(), 4),
    "to",
    round(retrieved_news_df["similarity_score"].max(), 4)
)

Retrieved news prepared successfully.
Selected articles: 10
Similarity score range: 0.5442 to 0.6268

In [13]:
print("========== Retrieved News Quality Check ==========")

print("Retrieved articles:", len(retrieved_news_df))
print(
    "Duplicate links:",
    retrieved_news_df["link"].duplicated().sum()
)
print(
    "Missing titles:",
    retrieved_news_df["title"].isna().sum()
)
print(
    "Missing links:",
    retrieved_news_df["link"].isna().sum()
)
print(
    "Scores sorted descending:",
    retrieved_news_df["similarity_score"].is_monotonic_decreasing
)

========== Retrieved News Quality Check ==========
Retrieved articles: 10
Duplicate links: 0
Missing titles: 0
Missing links: 0
Scores sorted descending: True

In [14]:
# Review the relevance of the top 10 retrieved news articles

for _, row in retrieved_news_df.iterrows():
    print("\n" + "=" * 90)
    print("Rank:", row["similarity_rank"])
    print("Similarity score:", round(row["similarity_score"], 4))
    print("Title:", row["title"])
    print("Source:", row["source"])
    print("Published (UTC):", row["published_at_utc"])

    summary = row.get("summary")
    content = row.get("content")

    print("\nSummary:")
    print(summary if pd.notna(summary) else "None")

    print("\nContent preview:")
    print(str(content)[:600] if pd.notna(content) else "None")

==========================================================================================
Rank: 1
Similarity score: 0.6268
Title: Bitcoin Could Be Entering a New Bull Market Despite Latest Sell-Off
Source: BeInCrypto
Published (UTC): 2026-10-11 19:22:47+00:00

Summary:
BloFin Research says Bitcoin's new bull market remains intact despite the latest sell-off, as historical data suggests its boom-and-bust cycles are weakening.

Content preview:
Despite the market dip and liquidations over the past week, Bitcoin has seemingly entered a bull market, as the analysis of its 50-week moving average shows.

BloFin Research argues that Bitcoin's traditional four-year boom-and-bust cycle is gradually losing strength. Future rallies could deliver smaller gains, followed by shorter and less severe downturns.

The strongest evidence comes from Bitcoin's recovery above its 50-week moving average, a technical indicator that previously signaled bull-market transitions in 2015, 2019 and 2023.

Bitcoin reclaimed this level near $78,800 in September.

==========================================================================================
Rank: 2
Similarity score: 0.6261
Title: Bitcoin and ethereum prices today, Monday, October 12, 2026: How bond yields 'threaten' crypto prices
Source: Yahoo Personal Finance
Published (UTC): 2026-10-12 11:40:18+00:00

Summary:
Bitcoin opened at $83,673.01 on Monday, October 12, 2026, up 0.9% from Sunday's opening price. As of 7:25 a.m. ET this morning, bitcoin dipped to $83,280.11. Ethereum opened at $2,534.30, up 1.2% from Sunday's opening price. The price of ethereum moved slightly higher this morning to $2,543.06 as of 7:25 a.m. ET.

Content preview:
Bitcoin ( BTC-USD ) opened at $83,673.01 on Monday, October 12, 2026 , up 0.9% from Sunday's opening price. As of 7:25 a.m. ET this morning, bitcoin dipped to $83,280.11.

Ethereum ( ETH-USD ) opened at $2,534.30 on Monday, October 12, 2026 , up 1.2% from Sunday's opening price. The price of ethereum moved slightly higher this morning to $2,543.06 as of 7:25 a.m. ET.

Bitcoin and ethereum prices have regained some ground from lower opening prices on Friday, and are generally back in line with where prices opened last Thursday.

The same forces that drove crypto prices lower toward the end of l

==========================================================================================
Rank: 3
Similarity score: 0.6058
Title: Bitcoin slips to $82.6k as rise in oil prices weigh on risk sentiment
Source: Investing.com
Published (UTC): 2026-10-12 07:08:56+00:00

Summary:
Investing.com -- Bitcoin edged lower on Monday, remaining under pressure amid an increase in oil prices driven by geopolitical tensions, including the deadly strikes in Saudi Arabia over the weekend.

Content preview:
Investing.com -- Bitcoin edged lower on Monday, remaining under pressure amid an increase in oil prices driven by geopolitical tensions, including the deadly strikes in Saudi Arabia over the weekend.

Before you buy NVIDIA: our AI model's stock picks are beating the market by 120%+. See the list now »

The world's largest crypto slid 1.3% to $82,553.7 by 18:01 ET (22:01 GMT). It had fallen about 2% last week, with outflows from spot U.S. exchange-traded funds lending some pressure.

Broader crypto prices were also rangebound on Monday, continuing a sluggish start to October.

Bitcoin and broad

==========================================================================================
Rank: 4
Similarity score: 0.5842
Title: Bitcoin Ranges Near $83K as Traders Look to US Inflation Data
Source: decrypt
Published (UTC): 2026-10-12 11:41:50+00:00

Summary:
October rate-hike odds have slumped, but analysts say Treasury yields at two-decade highs are still keeping a lid on risk appetite.

Content preview:
Bitcoin inched higher on Monday, trading at $83,327, up 0.6% over the past 24 hours, according to CoinGecko data. The asset is still down 2.9% over the past week.

The cryptocurrency has "struggled against an increasingly challenging macroeconomic backdrop," Daniela Hathorn, senior market analyst at Capital.com, told Decrypt .

"Rising energy prices have reignited inflation concerns, pushing US Treasury yields higher and strengthening the dollar as investors reassess the Federal Reserve's interest-rate trajectory," she said. "Despite its reputation as a potential alternative store of value, re

==========================================================================================
Rank: 5
Similarity score: 0.5764
Title: Bitcoin Tests Average Buyer’s Break-Even As ETF Outflows Clash With Wall Street Buying
Source: Stocktwits
Published (UTC): 2026-10-10 17:34:25+00:00

Summary:
Darkfost said the market was oscillating around the $80,500 line in a pattern resembling late 2025 and early 2026, with the level holding as support for now.

Content preview:
Bitcoin traded almost flat on Saturday, hovering just above $82,900.

CryptoQuant Darkfost analyst described this level as the average holder's break-even point.

On Wall Street, Fidelity's FBTC bought $354.1 million of Bitcoin over 20 trading days while Morgan Stanley added 92 coins this week to reach 10,639 BTC.

Bitcoin (BTC) traded flat on Saturday, sitting just above the price at which the average holder was neither up nor down, as one analyst said the setup looked like a repeat of a pattern from late last year.

That line sat around $80,500, according to CryptoQuant analyst Darkfost. It

==========================================================================================
Rank: 6
Similarity score: 0.566
Title: Why Bitcoin Can Fall Before a Fed Rate Hike, Then Rally After It Happens
Source: MoneyLion
Published (UTC): 2026-10-12 17:00:27+00:00

Summary:
Bitcoin fell on rate hike rumors, then rallied after the Fed acted. Learn why markets price the future and how crypto fits into the investment mix.

Content preview:
Wall Street has an old saying: buy the rumor, sell the news. Bitcoin seems to be doing the opposite in 2026. It took a beating this September as traders bet on a Fed rate hike, then rallied once the Fed actually pulled the trigger. Sounds backward, but it makes more sense than it looks.

The answer lies in how markets price the future and how Bitcoin fits into the investment mix. Rate hikes reshape the competition for investor dollars, and crypto has a complicated relationship with risk. Let's break down the moving parts.

Every investor is shopping around. When rates rise, Treasury bonds, sav

==========================================================================================
Rank: 7
Similarity score: 0.5593
Title: Bitcoin struggles above $83,000 a year after $19 billion crypto crash
Source: Investing.com
Published (UTC): 2026-10-11 05:54:26+00:00

Summary:
Investing.com -- Bitcoin remained above $83,000 on Sunday, roughly 34% below its record high, as investors marked one year since a historic $19 billion cryptocurrency liquidation event.

Content preview:
Investing.com -- Bitcoin remained above $83,000 on Sunday, roughly 34% below its record high, as investors marked one year since a historic $19 billion cryptocurrency liquidation event.

Before you buy NVIDIA: our AI model's stock picks are beating the market by 120%+. See the list now »

The world's largest cryptocurrency was trading at $83,062.8 as at 01:23 ET (05:23 GMT), having failed to recover its October 6, 2025, peak of $126,080.

The anniversary follows another volatile week in which Bitcoin fell to $80,308 before recovering towards $83,000, highlighting persistent concerns over lever

==========================================================================================
Rank: 8
Similarity score: 0.5523
Title: Crypto’s Crowded Longs Face a CPI Test, and a Hot Print Could Wipe Them Out
Source: CCN
Published (UTC): 2026-10-12 12:04:17+00:00

Summary:
Wednesday’s US CPI report could test crypto’s recovery, with hotter-than-expected inflation raising the risk of a selloff. Bitcoin faces resistance at $86,000-$88,000, while Ethereum and ...

Content preview:
Key Takeaways

Wednesday's US CPI report could test crypto's recovery, with hotter-than-expected inflation raising the risk of a selloff.

Bitcoin faces resistance at $86,000-$88,000, while Ethereum and XRP approach important support levels.

Weekly Bitcoin and Ethereum ETF outflows suggest weaker investment demand ahead of CPI and Thursday's PPI release.

Crypto's recovery faces a potentially unforgiving inflation test this week, with Bitcoin struggling below resistance and bullish traders vulnerable to another reversal.

September's US consumer price index report arrives Wednesday, Oct. 14,

==========================================================================================
Rank: 9
Similarity score: 0.5516
Title: Bitcoin Price Prediction: Golden Cross Signals 34% Average Rally for BTC
Source: FX Empire
Published (UTC): 2026-10-12 11:13:39+00:00

Summary:
Bitcoin nears a rare golden cross linked to 34% average gains as improving on-chain signals and US midterms raise hopes of an October bottom.

Content preview:
Bitcoin ( BTC ) is approaching a rare golden cross on its three-day chart, a bullish technical signal associated with an average 33.78% price rally across three historical examples.

The crossover could form as early as this week, potentially strengthening Bitcoin's broader recovery outlook as improving macroeconomic and on-chain conditions raise hopes of an October bottom.

Bitcoin's three-day chart shows its 20-period exponential moving average (20-3D EMA) approaching a crossover above the 200-period EMA (200-3D EMA) .

The formation, commonly known as a golden cross, occurs when a shorter-t

==========================================================================================
Rank: 10
Similarity score: 0.5442
Title: AI Price Prediction: Insights from Grok on Bitcoin’s Potential by Election Day
Source: 24/7 Wall St.
Published (UTC): 2026-10-11 12:12:14+00:00

Summary:
Grok crunched Bitcoin's price structure, fund flows, and midterm election history to land on a specific target for November 3. Whether its forecast holds depends on two price zones every Bitcoin holder should know right now.

Content preview:
Grok forecasts Bitcoin closes around $85,000 on November 3 midterm election day, just above its current $82,940 price.

Grok assigns a 30% chance Bitcoin exceeds $90,000 and a 25% chance it drops below $75,000 by election day.

Election results could swing Bitcoin 7% in either direction within a week, with congressional control influencing key crypto legislation.

Building a portfolio and living off one are two completely different skills, and almost nobody teaches the second. This problem is what The Definitive Guide to Retirement Income helps, and it is free today. Read more here. (Sponsor)

In [15]:
# Remove identifiable promotional paragraphs from retrieval text only
ad_patterns = [
    r"Before you buy NVIDIA",
    r"stock picks are beating the market",
    r"See the list now",
    r"See what 10M\+ investors are talking about",
    r"Get the Stocktwits Daily Rip",
    r"Building a portfolio and living off one",
    r"\(Sponsor\)"
]

def build_clean_article_text(row):
    parts = []

    title = row.get("title")
    summary = row.get("summary")
    content = row.get("content")

    if pd.notna(title) and str(title).strip():
        parts.append(f"Title: {str(title).strip()}")

    if pd.notna(summary) and str(summary).strip():
        parts.append(f"Summary: {str(summary).strip()}")

    if pd.notna(content) and str(content).strip():
        paragraphs = re.split(
            r"\n\s*\n",
            str(content).strip()
        )

        clean_paragraphs = [
            paragraph.strip()
            for paragraph in paragraphs
            if paragraph.strip()
            and not any(
                re.search(pattern, paragraph, flags=re.IGNORECASE)
                for pattern in ad_patterns
            )
        ]

        if clean_paragraphs:
            parts.append(
                "Content: " + "\n\n".join(clean_paragraphs)
            )

    return "\n".join(parts)


# Create clean retrieval texts without changing the source DataFrame
news_texts_clean = [
    build_clean_article_text(row)
    for _, row in keyword_filtered_df.iterrows()
]

print("========== Retrieval Text Cleaning ==========")
print("Candidate articles:", len(news_texts_clean))
print("Empty article texts:", sum(
    not text.strip() for text in news_texts_clean
))

print("\n========== Cleaned Example ==========")
print(news_texts_clean[2][:1000])

========== Retrieval Text Cleaning ==========
Candidate articles: 124
Empty article texts: 0

========== Cleaned Example ==========
Title: Cleveland Fed President Wants Small, Quick Rate Moves. What It Means for Bitcoin
Summary: Fed’s Hammack backs restrictive policy as December hike odds near 85% and Bitcoin slips in its strongest quarter.
Content: Cleveland Fed President Beth Hammack said that restrictive monetary policy is appropriate to return inflation to 2%. She also favors making smaller rate adjustments quickly rather than waiting and risking a larger correction later.

Rate futures now point to a hike in December, and the US dollar sits near an 18-month high. Meanwhile, Bitcoin (BTC) has slipped in October, historically one of its strongest months.

Hammack, a voting member of the Federal Open Market Committee (FOMC), spoke at the National Association for Business Economics annual meeting. She said the breadth of current price pressures means inflation will take some time to reach 2%.

August data shows the size of that gap. The personal consumption expenditures (PCE) price index, the Fed's preferred infla

In [16]:
# 1. Encode the same forecasting query
query_embedding_clean = sbert_model.encode(
    forecasting_query,
    convert_to_tensor=True,
    show_progress_bar=False
)

# 2. Re-encode the cleaned news texts
news_embeddings_clean = sbert_model.encode(
    news_texts_clean,
    convert_to_tensor=True,
    show_progress_bar=True
)

# 3. Recalculate cosine similarity
clean_scores = util.cos_sim(
    query_embedding_clean,
    news_embeddings_clean
).cpu().numpy().flatten()

# 4. Create a new results DataFrame
cleaned_semantic_results_df = keyword_filtered_df.copy()
cleaned_semantic_results_df["similarity_score"] = clean_scores

cleaned_semantic_results_df = (
    cleaned_semantic_results_df
    .sort_values("similarity_score", ascending=False)
    .reset_index(drop=True)
)

cleaned_semantic_results_df["similarity_rank"] = range(
    1, len(cleaned_semantic_results_df) + 1
)

# 5. Compare old and new rankings
rank_comparison = semantic_results_df[
    ["link", "title", "similarity_rank", "similarity_score"]
].merge(
    cleaned_semantic_results_df[
        ["link", "similarity_rank", "similarity_score"]
    ],
    on="link",
    suffixes=("_before", "_after"),
    validate="one_to_one"
)

# 6. Display the new Top 10
print("========== Cleaned SBERT Retrieval Summary ==========")
print("Candidate articles:", len(cleaned_semantic_results_df))
print("New embeddings shape:", tuple(news_embeddings_clean.shape))
print("Similarity scores recalculated:", len(clean_scores))

print("\n========== Top 10 After Cleaning ==========")
display(
    cleaned_semantic_results_df[
        [
            "similarity_rank",
            "title",
            "source",
            "similarity_score"
        ]
    ].head(10)
)

print("\n========== Ranking Comparison ==========")
old_top10_links = set(
    semantic_results_df.head(10)["link"]
)
new_top10_links = set(
    cleaned_semantic_results_df.head(10)["link"]
)

print("Top 10 articles retained:", len(old_top10_links & new_top10_links))
print("Articles entering Top 10:", len(new_top10_links - old_top10_links))
print("Articles leaving Top 10:", len(old_top10_links - new_top10_links))

Batches: 100%|██████████| 4/4 [00:02<00:00,  1.68it/s]

========== Cleaned SBERT Retrieval Summary ==========
Candidate articles: 124
New embeddings shape: (124, 384)
Similarity scores recalculated: 124

========== Top 10 After Cleaning ==========

,similarity_rank,title,source,similarity_score
0,1,Bitcoin Could Be Entering a New Bull Market De...,BeInCrypto,0.626807
1,2,"Bitcoin and ethereum prices today, Monday, Oct...",Yahoo Personal Finance,0.626133
2,3,AI Price Prediction: Insights from Grok on Bit...,24/7 Wall St.,0.613354
3,4,"Bitcoin struggles above $83,000 a year after $...",Investing.com,0.587221
4,5,Bitcoin Ranges Near $83K as Traders Look to US...,decrypt,0.584239
5,6,Bitcoin Tests Average Buyer’s Break-Even As ET...,Stocktwits,0.576397
6,7,"Why Bitcoin Can Fall Before a Fed Rate Hike, T...",MoneyLion,0.565969
7,8,Bitcoin’s Price Prediction: Will Global M2 Poi...,24/7 Wall St.,0.562907
8,9,"Bitcoin Dips to $80,000: How Other Coins Fared...",24/7 Wall St.,0.556565
9,10,Bitcoin Has Closed Four Straight Weeks Above I...,24/7 Wall St.,0.553092

========== Ranking Comparison ==========
Top 10 articles retained: 7
Articles entering Top 10: 3
Articles leaving Top 10: 3

In [17]:
# Update the final retrieved news using cleaned SBERT results

TOP_K = 10

retrieved_news_df = (
    cleaned_semantic_results_df
    .head(TOP_K)
    .copy()
)

print("========== Final Retrieved News ==========")
print("Candidate articles:", len(cleaned_semantic_results_df))
print("Retrieved articles:", len(retrieved_news_df))
print(
    "Similarity scores descending:",
    retrieved_news_df["similarity_score"].is_monotonic_decreasing
)

display(
    retrieved_news_df[
        [
            "similarity_rank",
            "title",
            "source",
            "published_at_utc",
            "similarity_score"
        ]
    ]
)

========== Final Retrieved News ==========
Candidate articles: 124
Retrieved articles: 10
Similarity scores descending: True

,similarity_rank,title,source,published_at_utc,similarity_score
0,1,Bitcoin Could Be Entering a New Bull Market De...,BeInCrypto,2026-10-11 19:22:47+00:00,0.626807
1,2,"Bitcoin and ethereum prices today, Monday, Oct...",Yahoo Personal Finance,2026-10-12 11:40:18+00:00,0.626133
2,3,AI Price Prediction: Insights from Grok on Bit...,24/7 Wall St.,2026-10-11 12:12:14+00:00,0.613354
3,4,"Bitcoin struggles above $83,000 a year after $...",Investing.com,2026-10-11 05:54:26+00:00,0.587221
4,5,Bitcoin Ranges Near $83K as Traders Look to US...,decrypt,2026-10-12 11:41:50+00:00,0.584239
5,6,Bitcoin Tests Average Buyer’s Break-Even As ET...,Stocktwits,2026-10-10 17:34:25+00:00,0.576397
6,7,"Why Bitcoin Can Fall Before a Fed Rate Hike, T...",MoneyLion,2026-10-12 17:00:27+00:00,0.565969
7,8,Bitcoin’s Price Prediction: Will Global M2 Poi...,24/7 Wall St.,2026-10-11 15:00:21+00:00,0.562907
8,9,"Bitcoin Dips to $80,000: How Other Coins Fared...",24/7 Wall St.,2026-10-10 10:00:32+00:00,0.556565
9,10,Bitcoin Has Closed Four Straight Weeks Above I...,24/7 Wall St.,2026-10-12 12:00:10+00:00,0.553092

In [18]:
print("========== Final SBERT Retrieval Quality Check ==========")

print("Candidate articles:", len(cleaned_semantic_results_df))
print("Retrieved articles:", len(retrieved_news_df))

print(
    "Duplicate links:",
    retrieved_news_df["link"].duplicated().sum()
)

print(
    "Missing titles:",
    retrieved_news_df["title"].isna().sum()
)

print(
    "Missing links:",
    retrieved_news_df["link"].isna().sum()
)

print(
    "Missing content:",
    retrieved_news_df["content"].isna().sum()
)

print(
    "Missing similarity scores:",
    retrieved_news_df["similarity_score"].isna().sum()
)

print(
    "Scores sorted descending:",
    retrieved_news_df["similarity_score"].is_monotonic_decreasing
)

print(
    "All scores finite:",
    np.isfinite(retrieved_news_df["similarity_score"]).all()
)

print("\nSimilarity score range:")
print(
    round(retrieved_news_df["similarity_score"].min(), 4),
    "to",
    round(retrieved_news_df["similarity_score"].max(), 4)
)

========== Final SBERT Retrieval Quality Check ==========
Candidate articles: 124
Retrieved articles: 10
Duplicate links: 0
Missing titles: 0
Missing links: 0
Missing content: 0
Missing similarity scores: 0
Scores sorted descending: True
All scores finite: True

Similarity score range:
0.5531 to 0.6268

In [19]:
# Map cleaned article texts back to their original article links
clean_text_by_link = dict(
    zip(keyword_filtered_df["link"], news_texts_clean)
)

cleaned_semantic_results_df["retrieval_text"] = (
    cleaned_semantic_results_df["link"].map(clean_text_by_link)
)

# Refresh the final Top 10 using cleaned SBERT rankings
TOP_K = 10

retrieved_news_df = (
    cleaned_semantic_results_df
    .head(TOP_K)
    .copy()
)

# Select the fields needed for downstream interpretation
columns_to_save = [
    "similarity_rank",
    "similarity_score",
    "title",
    "source",
    "published_at_utc",
    "link",
    "summary",
    "content",
    "retrieval_text",
    "content_status"
]

# Save to the project-level processed news directory
output_dir = Path("../data/news/processed")
output_dir.mkdir(parents=True, exist_ok=True)

output_path = output_dir / "bitcoin_news_retrieved_top10.csv"

retrieved_news_df[columns_to_save].to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Retrieved news saved successfully.")
print("File:", output_path)
print("Saved articles:", len(retrieved_news_df))
print(
    "Duplicate links:",
    retrieved_news_df["link"].duplicated().sum()
)
print(
    "Scores sorted descending:",
    retrieved_news_df["similarity_score"].is_monotonic_decreasing
)
print("Columns:", columns_to_save)

Retrieved news saved successfully.
File: ..\data\news\processed\bitcoin_news_retrieved_top10.csv
Saved articles: 10
Duplicate links: 0
Scores sorted descending: True
Columns: ['similarity_rank', 'similarity_score', 'title', 'source', 'published_at_utc', 'link', 'summary', 'content', 'retrieval_text', 'content_status']